Project Pizzeria {
note: '''
# Pizzeria
**Barcelona Activa**
'''
}

Enum employee_type {
    deliverer
    chef
}

Table deliver_address as A {
    id int [pk, increment]
    street_1 varchar(255) [not null]
    street_2 varchar(255) [note: 'If any description is needed']
    street_number varchar(20) [not null, note: 'Can contain chars: 10B']
    block_floor varchar(20) [note: 'Can contain chars: Entresuelo']
    floor_door varchar(20)
    city varchar(255) [ref: < AC.id,not null]
    postal_code varchar(32) [not null]
    country char(2) [not null, note: 'ISO 3166-1 alpha-2: ES']
}

Table city as AC {
    id int [pk, increment]
    province_id int [ref: > AP.id, not null]
    name varchar(255)
}
Table province as AP {
    id int [pk, increment]
    name varchar(255)
}

Table customer as C {
    id int [pk, increment]
    address_id int [ref: < A.id, not null]
    forename varchar(255) [not null]
    middlename varchar(255)
    surname varchar(255)
    telephone varchar(50)
}

Table product as P {
    id int [pk, increment]
    name varchar(255)
    description text
    image_url varchar(2083)
    price decimal(10,2)
}

Table pizza_categories as PC {
    id int [pk, increment]
    name varchar(255)
}

Table drink as D{
    id int [pk, ref: - P.id]
}

Table hamburger as H{
    id int [pk, ref: - P.id]
}

Table pizza as P {
    pizza_id int [pk, ref: - P.id]
    category int [ref: < PC.id, not null]
}

Table shop as S {
    id int [pk, increment]
    street_1 varchar(255) [not null]
    street_2 varchar(255) [note: 'If any description is needed']
    street_number varchar(20) [not null, note: 'Can contain chars: 10B']
    block_floor varchar(20) [note: 'Can contain chars: Entresuelo']
    floor_door varchar(20)
    city varchar(255) [ref: < AC.id,not null]
    postal_code varchar(32) [not null]
    country char(2) [not null, note: 'ISO 3166-1 alpha-2: ES']
}

Table employee as E {
    id int [pk, increment]
    shop int [ref: < S.id]
    nif varchar(10) [unique, not null]
    type employee_type
    forename varchar(255) [not null]
    middlename varchar(255)
    surname varchar(255)
    telephone varchar(50)
    street_1 varchar(255) [not null]
    street_2 varchar(255) [note: 'If any description is needed']
    street_number varchar(20) [not null, note: 'Can contain chars: 10B']
    block_floor varchar(20) [note: 'Can contain chars: Entresuelo']
    floor_door varchar(20)
    city varchar(255) [ref: < AC.id,not null]
    postal_code varchar(32) [not null]
    country char(2) [not null, note: 'ISO 3166-1 alpha-2: ES']
}

Table customer_order as CO {
    id int [pk, increment]
    shop_id int [ref: < S.id, not null]
    customer int [ref: > C.id, not null]
    deliver_address int [ref: > A.id]
    deliverer int [ref: > E.id]
    deliver boolean [default: false]
    ordered_at timestamp [default: `now()`]
    delivered_at datetime
    total_price decimal(10,2) [not null, note: 'It will be calculated: Every detail Total Price + %profit + taxes']

    indexes {
        (deliver, deliverer, ordered_at)
        (shop_id, id)
        (deliver_address, customer)
    }
}

Table customer_order_detail as COD {
    product_id int [ref: < P.id, not null]
    customer_order_id int [ref: < CO.id]
    quantity int [default: 1]
    price decimal(10,2) [not null]

    indexes {
        (product_id, customer_order_id) [pk]
    }
}

